/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"github.com/flashhhhh/Virtual-Machines-Management/custom-apiserver/pkg/apis/vms"
	"k8s.io/apimachinery/pkg/conversion"
)

// Convert_v1alpha1_VirtualMachineSpec_To_vms_VirtualMachineSpec is an autogenerated conversion function.
func Convert_v1alpha1_VirtualMachineSpec_To_vms_VirtualMachineSpec(in *VirtualMachineSpec, out *vms.VirtualMachineSpec, s conversion.Scope) error {
	out.Image = in.Image
	out.Size = in.Size
	out.SSHKeyIDs = in.SSHKeyIDs
	out.SubnetID = in.SubnetID
	out.SecurityGroupIDs = in.SecurityGroupIDs

	return nil
}

// Convert_vms_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec is an autogenerated conversion function.
func Convert_vms_VirtualMachineSpec_To_v1alpha1_VirtualMachineSpec(in *vms.VirtualMachineSpec, out *VirtualMachineSpec, s conversion.Scope) error {
	out.Image = in.Image
	out.Size = in.Size
	out.SSHKeyIDs = in.SSHKeyIDs
	out.SubnetID = in.SubnetID
	out.SecurityGroupIDs = in.SecurityGroupIDs

	return nil
}
