apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["virtualmachine.example.io"]
  resources: ["virtualmachine"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["virtualmachine.example.io"]
  resources: ["virtualmachine/status"]
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualmachine-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: virtualmachine-operator-controller-manager
  namespace: custom-controller-system
roleRef:
  kind: ClusterRole
  name: virtualmachine-operator-role
  apiGroup: rbac.authorization.k8s.io